import {test,expect} from '@playwright/test'
import {readFile} from 'node:fs/promises'
import {unzipSync} from 'fflate'
const key='un-soir-la-bas-upcoming-v1'
async function seed(page:import('@playwright/test').Page){
 await page.goto('/')
 await page.evaluate(key=>localStorage.setItem(key,JSON.stringify([{id:'test',destination:'Philippines',departure:'2027-02-01',endDate:'2027-02-20'}])),key)
 await page.goto('/#explore/test')
 await page.getByRole('button',{name:'Explorer',exact:true}).click()
}
test('envie géolocalisée, dédoublonnage, programme daté et sauvegarde ZIP',async({page,browser},info)=>{
 await seed(page)
 await page.getByRole('button',{name:/Chutes de Cambugahay Nature/}).click()
 const detail=page.getByRole('region',{name:'Fiche du lieu'})
 await detail.getByRole('button',{name:'Garder cette envie'}).click()
 await expect(detail.getByRole('status')).toContainText('Envie enregistrée')
 await detail.getByRole('button',{name:'Garder cette envie'}).click()
 await expect(detail.getByRole('status')).toContainText('déjà')
 await detail.getByLabel('Ajouter à une journée').fill('2027-02-09')
 await detail.getByRole('button',{name:'Ajouter à cette journée'}).click()
 await expect(detail.getByRole('status')).toContainText('Étape ajoutée')
 const trips=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!),key)
 expect(trips[0].plan.ideas).toHaveLength(1)
 expect(trips[0].plan.ideas[0]).toMatchObject({point:{lat:9.139,lon:123.627},category:'nature'})
 expect(trips[0].plan.stops[0]).toMatchObject({date:'2027-02-09',category:'nature'})
 await detail.getByRole('button',{name:'Fermer la fiche ×'}).click()
 await page.getByRole('button',{name:'Mon voyage',exact:true}).click()
 await page.getByLabel('Mes envies uniquement').check()
 await expect(page.locator('.discovery-place')).toHaveCount(1)
 await page.reload()
 await expect(page.locator('.discovery-place')).toHaveCount(2)
 await page.goto('/#tools')
 const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Sauvegarder dans Drive'}).click()
 const file=info.outputPath('discovery.zip');await (await pending).saveAs(file)
 const manifest=JSON.parse(new TextDecoder().decode(unzipSync(await readFile(file))['manifest.json']))
 expect(manifest.upcoming.trips[0].plan.ideas[0].point).toEqual({lat:9.139,lon:123.627})
 const freshContext=await browser.newContext(),fresh=await freshContext.newPage()
 await fresh.goto('/#tools');await fresh.getByLabel('Choisir une sauvegarde ZIP').setInputFiles(file)
 await expect(fresh.getByRole('heading',{name:'Restaurer ce carnet ?'})).toBeVisible()
 const safety=fresh.waitForEvent('download');await fresh.getByRole('button',{name:/télécharger la copie de sécurité/i}).click();await (await safety).saveAs(info.outputPath('safety.zip'))
 await fresh.getByRole('checkbox',{name:/je confirme que la copie de sécurité est téléchargée et vérifiée/i}).check()
 await fresh.getByRole('button',{name:'Restaurer ce carnet'}).click()
 await expect(fresh.getByRole('status')).toContainText('restaurées sur cet appareil')
 await fresh.goto('/#explore/test');await expect(fresh.locator('.discovery-place')).toHaveCount(2)
 await freshContext.close()
})
test('recherche de zone explicite, catégorie, téléphone et aucune requête au déplacement',async({page})=>{
 let count=0
 await page.route('**/photon.komoot.io/**',route=>route.fulfill({json:{features:[{geometry:{type:'Point',coordinates:[123.627,9.139]},properties:{name:'Lazi',country:'Philippines'}}]}}))
 await page.route('**/photon.komoot.io/reverse?**',route=>{count++;return route.fulfill({json:{features:[{geometry:{type:'Point',coordinates:[123.63,9.14]},properties:{osm_type:'N',osm_id:42,name:'Café de test',extra:{phone:'+63 1234'}}}]}})})
 await seed(page)
 await page.getByLabel('Une destination ou un lieu').fill('Lazi')
 await page.getByRole('button',{name:'Rechercher',exact:true}).click()
 await expect(page.locator('.discovery-place')).toHaveCount(1)
 await expect(page.locator('.discovery-place')).toContainText('Lazi')
 await page.getByRole('button',{name:/Manger/,exact:false}).click()
 await page.getByRole('button',{name:'Rechercher dans cette zone'}).click()
 await expect(page.locator('.discovery-place')).toContainText('Café de test')
 expect(count).toBe(1)
 await page.locator('.leaflet-control-zoom-in').click()
 expect(count).toBe(1)
 await page.locator('.discovery-place').click()
 await expect(page.getByRole('link',{name:'+63 1234',exact:true})).toHaveAttribute('href','tel:+631234')
})
test('mobile, consultation hors réseau et refus de géolocalisation',async({page},info)=>{
 await page.setViewportSize({width:390,height:844})
 await page.addInitScript(()=>{navigator.geolocation.getCurrentPosition=(_success,error)=>error?.({code:1,message:'refused',PERMISSION_DENIED:1,POSITION_UNAVAILABLE:2,TIMEOUT:3})})
 await page.route('**/tile.openstreetmap.org/**',route=>route.abort())
 await seed(page)
 await page.getByRole('button',{name:'Autour de moi',exact:true}).click()
 await expect(page.getByRole('status')).toContainText('autorisation refusée')
 await page.getByRole('button',{name:'Utiliser la liste'}).click()
 await page.locator('.discovery-place').filter({hasText:'Cambugahay'}).click()
 await expect(page.getByRole('region',{name:'Fiche du lieu'})).toBeVisible()
 await expect(page.getByRole('button',{name:'Garder cette envie'})).toBeVisible()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBeLessThanOrEqual(1)
 await page.screenshot({path:info.outputPath('discovery-mobile.png')})
 await page.getByRole('button',{name:'Fermer la fiche ×'}).click()
 await page.setViewportSize({width:1440,height:1000})
 await page.getByRole('button',{name:'Afficher la carte'}).click()
 await page.screenshot({path:info.outputPath('discovery-desktop.png'),fullPage:true})
})
test('échec du stockage et dates hors séjour ne modifient rien',async({page})=>{
 await seed(page)
 await page.locator('.discovery-place').first().click()
 await page.getByLabel('Ajouter à une journée').fill('2028-01-01')
 await page.getByRole('button',{name:'Ajouter à cette journée'}).click()
 await expect(page.getByRole('region',{name:'Fiche du lieu'}).getByRole('status')).toContainText('dates du voyage')
 await page.evaluate(()=>{Storage.prototype.setItem=()=>{throw new DOMException('quota','QuotaExceededError')}})
 await page.getByRole('button',{name:'Garder cette envie'}).click()
 await expect(page.getByRole('region',{name:'Fiche du lieu'}).getByRole('status')).toContainText('Rien n’a été ajouté')
 expect((await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!),key))[0].plan).toBeUndefined()
})
test('souvenirs, photos et retour au chapitre des Visayas',async({page})=>{
 await page.goto('/#visayas');await page.getByRole('button',{name:'Ajouter cet exemple à mes voyages'}).click()
 await expect(page.getByRole('link',{name:'Ouvrir mon programme'})).toBeVisible()
 await page.getByRole('link',{name:'Ouvrir mon programme'}).click()
 await page.getByRole('navigation',{name:'Navigation du voyage'}).getByRole('link',{name:'Carte',exact:true}).click()
 await page.getByRole('button',{name:'Mes souvenirs',exact:true}).click()
 await expect(page.locator('.discovery-place')).toHaveCount(20)
 await page.locator('.discovery-place').first().click()
 await expect(page.locator('.discovery-detail img')).toBeVisible()
 await page.getByRole('link',{name:'Lire le souvenir'}).click()
 await expect(page).toHaveURL(/#journey\//)
})

test('panne de recherche et modifications concurrentes préservent les voyages',async({page})=>{
 await seed(page)
 await page.route('**/photon.komoot.io/**',route=>route.abort())
 await page.getByLabel('Une destination ou un lieu').fill('Lazi')
 await page.getByRole('button',{name:'Rechercher',exact:true}).click()
 await expect(page.getByRole('status')).toContainText('Connexion au service impossible')
 await expect(page.locator('.discovery-place')).toHaveCount(5)
 await page.locator('.discovery-place').first().click()
 await page.evaluate(key=>{const trips=JSON.parse(localStorage.getItem(key)!);trips.push({id:'other',destination:'Autre voyage',departure:'2027-03-01'});localStorage.setItem(key,JSON.stringify(trips))},key)
 await page.getByRole('button',{name:'Garder cette envie'}).click()
 expect(await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!).length,key)).toBe(2)
 await page.evaluate(key=>localStorage.setItem(key,'damaged'),key)
 await page.getByRole('button',{name:'Garder cette envie'}).click()
 await expect(page.getByRole('region',{name:'Fiche du lieu'}).getByRole('status')).toContainText('Impossible de lire')
 expect(await page.evaluate(key=>localStorage.getItem(key),key)).toBe('damaged')
})
