import {test,expect} from '@playwright/test'
test('voyage en cours prioritaire, lecture puis modification et navigation carte',async({page},info)=>{
  await page.goto('/#visayas')
  await page.getByRole('button',{name:'Ajouter cet exemple à mes voyages'}).click()
  await expect(page.getByRole('link',{name:'Ouvrir mon programme'})).toBeVisible()
  await page.goto('/#carnet')
  await expect(page.getByRole('link',{name:'Voir ma journée'})).toBeVisible()
  await expect(page.locator('.next-landscape img')).toBeVisible()
  await page.setViewportSize({width:1440,height:1000})
  await page.screenshot({path:info.outputPath('home-desktop.png'),fullPage:true})
  await page.setViewportSize({width:390,height:844})
  await page.screenshot({path:info.outputPath('home-mobile.png'),fullPage:true})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBeLessThanOrEqual(1)
  await page.getByRole('link',{name:'Voir ma journée'}).click()
  const nav=page.getByRole('navigation',{name:'Navigation du voyage'})
  await nav.getByRole('link',{name:'Programme',exact:true}).click()
  await expect(page.locator('.daily-stop').first()).toBeVisible()
  await expect(page.locator('.daily-stop input').first()).not.toBeVisible()
  await page.locator('.day-edit summary').first().click()
  await expect(page.locator('.daily-stop input').first()).toBeVisible()
  await page.locator('.day-edit summary').first().click()
  await nav.getByRole('link',{name:'Carte',exact:true}).click()
  await expect(page.locator('.leaflet-container')).toBeVisible()
  await nav.getByRole('link',{name:'Programme',exact:true}).click()
  await expect(page.locator('.daily-stop').first()).toBeVisible()
  await page.screenshot({path:info.outputPath('programme-mobile.png'),fullPage:true})
  await nav.getByRole('link',{name:'Carnet',exact:true}).click()
  await expect(page.getByTestId('journal-chapter-card')).toHaveCount(20)
  await page.getByRole('button',{name:'Créer une journée'}).click()
  await expect(page).toHaveURL(/#trip-create\//)
})
