import { expect, test } from '@playwright/test'

function future(days: number) {
  const date = new Date(); date.setHours(12, 0, 0, 0); date.setDate(date.getDate() + days)
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`
}

async function addTrip(page: import('@playwright/test').Page, name: string, days: number) {
  await page.getByRole('button', { name: 'Préparer un voyage' }).click()
  await page.getByLabel('Destination').fill(name)
  await page.getByLabel('Date de départ').fill(future(days))
  await page.getByRole('button', { name: 'Ajouter au décompte' }).click()
}

async function writeChapter(page: import('@playwright/test').Page, title: string, story: string) {
  await page.getByRole('button', { name: 'Raconter cette journée' }).click()
  await page.getByLabel('Le titre de votre journée').fill(title)
  await page.getByLabel('Votre récit, à votre façon').fill(story)
  await page.getByRole('button', { name: 'Prévisualiser' }).click()
  await page.getByRole('button', { name: 'Ajouter au voyage' }).click()
  await expect(page.getByRole('heading', { name: title })).toBeVisible()
}

test('deux voyages gardent leurs journées, édition, partage et liens directs séparés', async ({ page }) => {
  await page.goto('/')
  await addTrip(page, 'Kyoto', 20)
  await addTrip(page, 'Lisbonne', 40)
  await page.getByRole('button', { name: 'Planifier Kyoto' }).click()
  await page.getByRole('button', { name: 'Ouvrir le carnet de Kyoto' }).click()
  await expect(page.getByRole('button', { name: 'Partager' })).toBeDisabled()
  await writeChapter(page, 'Le jardin du matin', 'Nous avons vu les érables.')
  const kyotoChapter = page.url()
  await page.reload()
  await expect(page.getByText('Nous avons vu les érables.')).toBeVisible()
  await page.getByRole('button', { name: 'Modifier cette journée' }).click()
  await page.reload()
  await expect(page.getByLabel('Le titre de votre journée')).toHaveValue('Le jardin du matin')
  await page.getByLabel('Votre récit, à votre façon').fill('La pluie sur les érables.')
  await page.getByRole('button', { name: 'Prévisualiser' }).click()
  await page.getByRole('button', { name: 'Ajouter au voyage' }).click()
  await expect(page.getByText('La pluie sur les érables.')).toBeVisible()
  await page.getByRole('navigation', { name: 'Navigation principale' }).getByRole('button', { name: 'Partager' }).click()
  await expect(page).toHaveURL(/#journal-share\//)
  await page.getByRole('link', { name: 'Retour à cette journée' }).click()
  await page.getByRole('button', { name: 'Préparer le partage' }).click()
  await expect(page.getByText('Le jardin du matin').first()).toBeVisible()
  await page.getByRole('link', { name: 'Retour à cette journée' }).click()
  await expect(page.getByText('La pluie sur les érables.')).toBeVisible()
  await page.goto('/')
  await page.getByRole('button', { name: 'Ouvrir Lisbonne' }).click()
  await page.getByRole('button', { name: 'Ouvrir le carnet de Lisbonne' }).click()
  await expect(page.getByText('Le jardin du matin')).toHaveCount(0)
  await writeChapter(page, 'Le soir sur le Tage', 'Une lumière douce sur l’eau.')
  await page.goto('/')
  await page.getByRole('button', { name: 'Modifier Kyoto' }).click()
  await page.getByLabel('Destination').fill('Kyoto et Nara')
  await page.getByRole('button', { name: 'Enregistrer les modifications' }).click()
  await expect(page.getByRole('button', { name: 'Ouvrir le carnet de Kyoto et Nara' })).toBeVisible()
  await page.goto(kyotoChapter)
  await expect(page.getByText('La pluie sur les érables.')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Le jardin du matin' })).toBeVisible()
  const journals = await page.evaluate(() => JSON.parse(localStorage.getItem('un-soir-la-bas-journals-v1') || '{}'))
  expect(journals.journals).toHaveLength(2)
  expect(journals.journals.map((item: { chapters: unknown[] }) => item.chapters.length)).toEqual([1, 1])
  expect(await page.evaluate(() => localStorage.getItem('philippines-trip'))).toBeNull()
})

test('ancien chapitre Philippines et voyage retiré restent consultables', async ({ page }) => {
  await page.goto('/')
  await page.evaluate(() => localStorage.setItem('philippines-trip', JSON.stringify({ version: 1, drafts: [{ id: 'legacy-day', title: 'Notre ancien jour', memories: 'Souvenir', tone: 'Spontané', story: 'Une page conservée.', media: [], coverId: '', status: 'draft' }] })))
  await page.reload()
  await page.goto('/#draft/legacy-day')
  await expect(page.getByText('Une page conservée.')).toBeVisible()
  await page.goto('/')
  await addTrip(page, 'Kyoto', 20)
  await page.getByRole('button', { name: 'Planifier Kyoto' }).click()
  await page.getByRole('button', { name: 'Ouvrir le carnet de Kyoto' }).click()
  await writeChapter(page, 'Un matin', 'La vraie journée.')
  await page.goto('/')
  await page.getByRole('button', { name: 'Retirer Kyoto' }).click()
  await expect(page.getByRole('button', { name: 'Ouvrir le carnet de Kyoto' })).toBeVisible()
  await page.getByRole('button', { name: 'Ouvrir le carnet de Kyoto' }).click()
  await expect(page.getByText('Un matin')).toBeVisible()
})

test('nouveau récit de voyage ne prétend pas être aux Philippines', async ({ page }) => {
  await page.goto('/')
  await addTrip(page, 'Kyoto', 20)
  await page.getByRole('button', { name: 'Planifier Kyoto' }).click()
  await page.getByRole('button', { name: 'Ouvrir le carnet de Kyoto' }).click()
  await page.getByRole('button', { name: 'Raconter cette journée' }).click()
  await expect(page.getByText('PHILIPPINES 2027')).toHaveCount(0)
  await page.getByLabel('Souvenirs de la journée').fill('Un temple au matin')
  await page.getByRole('button', { name: 'Générer le récit' }).click()
  await expect(page.getByLabel('Votre récit, à votre façon')).not.toContainText('Philippines')
})

test('carnet personnel lisible sur téléphone', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await addTrip(page, 'Kyoto', 20)
  await page.getByRole('button', { name: 'Planifier Kyoto' }).click()
  await page.getByRole('button', { name: 'Ouvrir le carnet de Kyoto' }).click()
  await page.screenshot({ path: testInfo.outputPath('journal-mobile.png'), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBeLessThanOrEqual(1)
  await writeChapter(page, 'Le jardin du matin', 'Un instant sous les arbres.')
  await page.getByRole('button', { name: 'Retour au carnet' }).click()
  await expect(page.getByTestId('journal-chapter-card')).toHaveCount(1)
  expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBeLessThanOrEqual(1)
})
