import {test,expect} from '@playwright/test'
import {readFile} from 'node:fs/promises'
import {unzipSync} from 'fflate'

test('vingt journées consultables, photos réelles et film sans écrire dans les voyages',async({page},testInfo)=>{
  await page.setViewportSize({width:390,height:844})
  await page.goto('/#visayas')
  await expect(page.getByRole('navigation',{name:'Les vingt journées'}).getByRole('button')).toHaveCount(20)
  await page.getByRole('button',{name:'JOUR 9 Siquijor',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Le vert et l’eau de Cambugahay'})).toBeVisible()
  await expect.poll(()=>page.locator('.visayas-day img').evaluate((img:HTMLImageElement)=>img.complete&&img.naturalWidth>0)).toBe(true)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBeLessThanOrEqual(1)
  await page.screenshot({path:testInfo.outputPath('visayas-mobile.png'),fullPage:true})
  expect(await page.evaluate(()=>localStorage.getItem('un-soir-la-bas-upcoming-v1'))).toBeNull()
  await page.getByRole('link',{name:'Explorer le voyage animé'}).click()
  await expect(page.locator('.journey-itinerary li')).toHaveCount(25)
  await expect(page.getByRole('button',{name:'Lancer le voyage'})).toBeEnabled({timeout:20000})
  await page.getByRole('button',{name:'Créer mon film'}).click()
  await expect(page.getByLabel('Illustrer toutes les liaisons sans calcul routier')).toBeChecked()
  await expect(page.locator('.film-note')).toContainText('4 min 05 s')
  expect(await page.evaluate(()=>localStorage.getItem('un-soir-la-bas-upcoming-v1'))).toBeNull()
})

test('copie complète, dates, préservation, sauvegarde ZIP et photos embarquées',async({page},testInfo)=>{
  await page.goto('/')
  await page.evaluate(()=>localStorage.setItem('un-soir-la-bas-upcoming-v1',JSON.stringify([{id:'existing',destination:'Voyage à garder',departure:'2027-01-01'}])))
  await page.goto('/#visayas')
  await page.getByLabel('Date de départ de l’exemple').fill('2027-02-01')
  await page.getByRole('button',{name:'Ajouter cet exemple à mes voyages'}).click()
  await expect(page.getByRole('link',{name:'Ouvrir mon programme'})).toBeVisible({timeout:20000})
  const data=await page.evaluate(()=>({trips:JSON.parse(localStorage.getItem('un-soir-la-bas-upcoming-v1')!),journals:JSON.parse(localStorage.getItem('un-soir-la-bas-journals-v1')!),bytes:localStorage.getItem('un-soir-la-bas-journals-v1')!.length}))
  expect(data.trips).toHaveLength(2);expect(data.trips[0].destination).toBe('Voyage à garder')
  expect(data.trips[1]).toMatchObject({departure:'2027-02-01',endDate:'2027-02-20'})
  expect(data.trips[1].plan.stops).toHaveLength(25)
  expect(new Set(data.trips[1].plan.stops.map((s:{date:string})=>s.date)).size).toBe(20)
  expect(data.journals.journals[0].chapters).toHaveLength(20)
  expect(data.journals.journals[0].chapters.every((c:{media:{src:string}[]})=>c.media[0].src.startsWith('data:image/jpeg;base64,'))).toBe(true)
  expect(data.bytes).toBeLessThan(3_000_000)
  await page.reload();await expect(page.getByRole('button',{name:'Ajouter cet exemple à mes voyages'})).toHaveCount(0)
  await page.getByRole('link',{name:'Carnet, photos et copie de lecture'}).click()
  await expect(page.getByTestId('journal-chapter-card')).toHaveCount(20)
  await page.goto('/#tools')
  const pending=page.waitForEvent('download')
  await page.getByRole('button',{name:'Sauvegarder dans Drive'}).click()
  const download=await pending,path=testInfo.outputPath('visayas.zip');await download.saveAs(path)
  const files=unzipSync(await readFile(path)),manifest=JSON.parse(new TextDecoder().decode(files['manifest.json']))
  expect(manifest.media).toBe(20)
  expect(manifest.upcoming.trips[1].plan.stops).toHaveLength(25)
})

test('un échec de stockage ne laisse pas un demi-voyage',async({page})=>{
  await page.goto('/#visayas')
  await page.evaluate(()=>{const original=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key==='un-soir-la-bas-upcoming-v1')throw new DOMException('Quota','QuotaExceededError');return original.call(this,key,value)}})
  await page.getByRole('button',{name:'Ajouter cet exemple à mes voyages'}).click()
  await expect(page.getByRole('status')).toContainText('Stockage insuffisant',{timeout:20000})
  expect(await page.evaluate(()=>localStorage.getItem('un-soir-la-bas-journals-v1'))).toBeNull()
  expect(await page.evaluate(()=>localStorage.getItem('un-soir-la-bas-upcoming-v1'))).toBeNull()
})
