import { useState } from 'react'
import { visayasDays } from '../visayas-days'
import { installVisayas, visayasCredits, visayasId } from '../visayas-demo'
import { calendarDate, readUpcoming } from '../upcoming-trips'
import './visayas-showcase.css'

export default function VisayasShowcase(){
  const [day,setDay]=useState(0),[departure,setDeparture]=useState(()=>calendarDate(new Date()))
  const [busy,setBusy]=useState(false),[message,setMessage]=useState('')
  const [installed,setInstalled]=useState(()=>readUpcoming().trips.some(t=>t.id===visayasId))
  const selected=visayasDays[day],credit=visayasCredits[selected.photo]
  return <section className="visayas-showcase page-width">
    <header className="visayas-hero"><img src="/assets/visayas/apo.jpg" alt="Bateaux traditionnels devant Apo Island, Negros oriental"/><div><p className="eyebrow">Le grand voyage de démonstration</p><h1>Vingt jours.<br/>Les Visayas au fil de l’eau.</h1><p>Cebu · Bohol · Siquijor · Negros oriental</p><a className="button button-light" href="#motion/visayas">Explorer le voyage animé →</a></div></header>
    <p className="local-note">Photo : {visayasCredits.apo.author} · {visayasCredits.apo.license}. <a href={visayasCredits.apo.source}>Source</a> · <a href={visayasCredits.apo.licenseUrl}>Licence</a>. Miniature recadrée.</p>
    <div className="visayas-intro"><div><p className="eyebrow">Un exemple complet, prêt à explorer</p><h2>Préparer. Vivre. Raconter.</h2><p>20 journées racontées, 25 points de parcours, des traversées, des pauses et un carnet illustré. Découvrez le film, puis créez votre copie pour essayer toutes les fonctions.</p><p><strong>Scénario fictif.</strong> Les lieux existent ; les récits sont inventés. Aucun hôtel ni billet réservé, aucun horaire garanti. Les photos documentaires illustrent leur île ou leur région : elles ne prétendent pas avoir été prises pendant ce voyage.</p></div>
    <aside className="visayas-copy"><h2>Essayez avec votre copie</h2><p>Vos voyages restent conservés. L’exemple sera ajouté séparément, avec ses photos accessibles localement.</p>{installed?<><a className="button" href={`#plan/${visayasId}`}>Ouvrir mon programme →</a><a href={`#today/${visayasId}`}>Aujourd’hui et souvenir rapide</a><a href={`#trip/${visayasId}`}>Carnet, photos et copie de lecture</a><a href={`#motion/${visayasId}`}>Personnaliser le film</a><a href="#tools">Hors connexion et sauvegarde ZIP</a></>:<form onSubmit={async event=>{event.preventDefault();setBusy(true);setMessage('Préparation des photos et des vingt journées…');try{await installVisayas(departure);setInstalled(true);setMessage('Votre copie est prête. Ouvrez le programme ou le carnet.')}catch(error){setMessage(error instanceof Error?error.message:'Copie impossible.')}finally{setBusy(false)}}}><label>Date de départ de l’exemple<input type="date" required value={departure} disabled={busy} onChange={e=>setDeparture(e.target.value)}/></label><button className="button" disabled={busy}>{busy?'Préparation…':'Ajouter cet exemple à mes voyages'}</button></form>}{message&&<p role="status">{message}</p>}</aside></div>
    <nav className="visayas-days" aria-label="Les vingt journées">{visayasDays.map((d,i)=><button key={d.place} aria-pressed={day===i} onClick={()=>setDay(i)}><small>JOUR {i+1}</small><strong>{d.island}</strong></button>)}</nav>
    <article className="visayas-day"><div><img src={`/assets/visayas/${selected.photo}.jpg`} alt={credit.title}/><p className="local-note">Illustration : {credit.title} — {credit.author}. <a href={credit.source}>Source</a> · <a href={credit.licenseUrl}>{credit.license}</a>. Miniature recadrée.</p></div><div><p className="eyebrow">Jour {day+1} · {selected.place}</p><h2>{selected.title}</h2><dl><dt>Matin</dt><dd>{selected.morning}</dd><dt>Après-midi</dt><dd>{selected.afternoon}</dd><dt>Soir</dt><dd>{selected.evening}</dd><dt>Nuit suggérée</dt><dd>{selected.night} · hébergement à choisir</dd></dl><blockquote><small>Extrait fictif du carnet</small><p>{selected.story}</p></blockquote></div></article>
    <section className="visayas-features"><h2>Une visite guidée de l’application</h2><ol><li><strong>Préparer :</strong> ouvrez la carte, filtrez une journée et cliquez sur un repère pour lire sa fiche.</li><li><strong>Vivre :</strong> dans Aujourd’hui, ajoutez un texte ou une photo au chapitre de l’escale.</li><li><strong>Emporter :</strong> téléchargez l’accès hors connexion depuis la préparation.</li><li><strong>Raconter :</strong> explorez les 20 chapitres et exportez une copie de lecture avec les crédits photo.</li><li><strong>Monter :</strong> ouvrez le film, choisissez les photos et légendes, puis votre musique. Sélectionnez les liaisons illustrées pour un aperçu sans calcul routier.</li><li><strong>Conserver :</strong> exportez une archive ZIP depuis les outils du carnet.</li></ol></section>
    <p className="local-note">Parcours proposé, points GPS indicatifs. Confirmez les accès, la météo, les ports et les transports avant toute réservation. Vols internationaux hors programme. Sources consultées le 25 septembre 2026 : <a href="https://philippines.travel/">Office du tourisme philippin</a>, <a href="https://www.oceanjet.net/">OceanJet</a>, <a href="https://tpb.gov.ph/wp-content/uploads/2023/10/R7-Central-Visayas_map.pdf">carte touristique des Visayas</a>. <a href="/assets/visayas/credits.json">Crédits des six photographies</a>.</p>
  </section>
}
