import type { PersonalJournal } from './trip-journals'
import type { PlanStop } from './upcoming-trips'
import { transportModes } from './upcoming-trips'

const escape = (text: string) => text.replace(/[&<>"']/g,char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!))
export function readingCopy(journal: PersonalJournal, stops: PlanStop[]): Blob {
  const image = (src: string, name: string) => /^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/]+={0,2}$/.test(src) ? `<figure><img src="${src}" alt="${escape(name)}" loading="lazy"><figcaption>${escape(name)}</figcaption></figure>` : ''
  const chapters = journal.chapters.map((chapter,index) => {
    const media = [...chapter.media].sort((a,b) => Number(b.id === chapter.coverId)-Number(a.id === chapter.coverId))
    return `<article id="chapitre-${index+1}"><p class="eyebrow">CHAPITRE ${index+1}</p><h2>${escape(chapter.title)}</h2>${media[0] ? image(media[0].src,media[0].name) : ''}<div class="story">${escape(chapter.story)}</div><div class="photos">${media.slice(1).map(m=>image(m.src,m.name)).join('')}</div><a href="#sommaire">Retour au sommaire ↑</a></article>`
  }).join('')
  const html = `<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src data:; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><title>${escape(journal.destination)} — Un soir là-bas</title><style>
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#f6f3eb;color:#243e35;font:17px/1.8 Arial,sans-serif}main{max-width:900px;margin:auto;padding:40px 24px}header{padding:60px 0;border-bottom:1px solid #cbd1c2}.brand{font:24px Georgia,serif}.eyebrow{font:12px/1.6 Arial,sans-serif;letter-spacing:.15em;color:#47665e}h1,h2{font-family:Georgia,serif;font-weight:400;line-height:1.1;overflow-wrap:anywhere}h1{font-size:clamp(40px,8vw,78px)}h2{font-size:clamp(30px,5vw,50px)}a{color:#245e61}nav{padding:24px 0}nav li{padding:5px 0}article{padding:48px 0;border-top:1px solid #cbd1c2;break-before:page}.story{white-space:pre-wrap;overflow-wrap:anywhere;margin:28px 0}figure{margin:24px 0;break-inside:avoid}img{display:block;width:100%;max-height:680px;object-fit:contain;background:#e9ede5}figcaption{font-size:12px;color:#526860}.photos{display:grid;grid-template-columns:1fr 1fr;gap:18px}.photos img{height:300px;object-fit:contain}.route{padding-left:24px}.route small{color:#526860}footer{border-top:1px solid #cbd1c2;padding-top:24px;font-size:13px;color:#526860}@media(max-width:550px){.photos{grid-template-columns:1fr}header{padding:25px 0}}@media print{body{background:white}main{max-width:none;padding:0}nav,article>a{display:none}img{max-height:18cm}.photos img{height:auto}}
</style></head><body><main><header><p class="brand">un soir <em>là-bas</em></p><p class="eyebrow">LE CARNET DU VOYAGE</p><h1>${escape(journal.destination)}</h1>${journal.departure ? `<p>Départ · ${escape(journal.departure)}</p>` : ''}<p>${journal.chapters.length} chapitre${journal.chapters.length===1?'':'s'} · vos images et vos histoires</p></header><nav id="sommaire" aria-label="Sommaire"><h2>Au fil du voyage</h2><ol>${journal.chapters.map((c,i)=>`<li><a href="#chapitre-${i+1}">${escape(c.title)}</a></li>`).join('')}</ol></nav>${stops.length ? `<section><h2>Les escales</h2><ol class="route">${stops.map((s,i)=>`<li>${escape(s.place)} <small>${s.date ? `· ${escape(s.date)} ` : ''}${i>0&&s.transport?`· ${transportModes[s.transport]}`:''}</small></li>`).join('')}</ol></section>` : ''}${chapters}<footer>Copie de lecture créée le ${new Intl.DateTimeFormat('fr-FR',{dateStyle:'long'}).format(new Date())}. Ce fichier contient les textes et photos sélectionnés du carnet et se lit sans connexion. Il ne synchronise aucune modification. Pour restaurer le carnet dans l’application, utilisez sa sauvegarde ZIP.</footer></main></body></html>`
  const blob = new Blob([html],{type:'text/html;charset=utf-8'})
  if (blob.size > 25*1024*1024) throw new Error('Cette copie dépasse 25 Mo. Réduisez les photos avant de la partager.')
  return blob
}
